### ISSUE TITLE
Add option for custom closure template jar path

### ISSUE THREAD

**Issue by robframpton** [Medium/soynode#65]
I would like to use the newest version of closure templates in my project. However, since [closure-templates](https://www.npmjs.com/package/closure-templates) hasn't been published in quite some time and the path to the jar file is [hardcoded](https://github.com/Medium/soynode/blob/master/lib/SoyCompiler.js#L26) I can't.

It would be great to have an option for a custom path to a jar file so that I have more control over what version is being used.

**Comment by nicks** [comment]
see discussion in https://github.com/Medium/soynode/pull/53. the problem is that there's a non-trivial dependency on JS support files, so adding a custom path to a jar file wouldn't be sufficient.

we would accept a PR to add support for injecting a custom jar/js pair, but i'm not sure what the api would look like.
